/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.crypto;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasCommands() {
        assertNotNull(Crypto.commands);
        assertTrue(Crypto.commands.size() > 0);
    }

    // Work through a few commands in sequence to ensure they work together as expected
}
